-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 01, 2024 at 02:55 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.1.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ruchidoctor`
--

-- --------------------------------------------------------

--
-- Table structure for table `ruchidoctor_personalitytests`
--

CREATE TABLE `ruchidoctor_personalitytests` (
  `id` varchar(24) DEFAULT NULL,
  `Question` varchar(8) DEFAULT NULL,
  `QA` varchar(104) DEFAULT NULL,
  `AA` varchar(2) DEFAULT NULL,
  `QB` varchar(112) DEFAULT NULL,
  `AB` varchar(2) DEFAULT NULL,
  `HA` varchar(118) DEFAULT NULL,
  `HB` varchar(151) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

--
-- Dumping data for table `ruchidoctor_personalitytests`
--

INSERT INTO `ruchidoctor_personalitytests` (`id`, `Question`, `QA`, `AA`, `QB`, `AB`, `HA`, `HB`) VALUES
('5e306f1cb31adad40ccc8941', '1', 'I\'ve been romantic and imaginative', 'E', 'I\'ve been pragmatic and down to earth', 'B', 'मैं रोमांटिक और कल्पनाशील रहा हूं', 'मैं व्यावहारिक और जमीन से जुड़ा हुआ हूं'),
('5e306f1cb31adad40ccc8942', '2', 'I have tended to take on confrontations', 'G', 'I have tended to avoid confrontations', 'A', 'मैं टकराव मोल लेने की प्रवृत्ति रखता हूं', 'मैं टकराव से बचने की प्रवृत्ति रखता हूं'),
('5e306f1cb31adad40ccc8943', '3', 'I have typically been diplomatic, charming, and ambitious', 'C', 'I have typically been direct, formal, and idealistic', 'D', 'मैं आमतौर पर कूटनीतिक, आकर्षक और महत्वाकांक्षी रहा हूं', 'मैं आमतौर पर प्रत्यक्ष, औपचारिक और आदर्शवादी रहा हूं'),
('5e306f1cb31adad40ccc8944', '4', 'I have tended to be focused and intense', 'H', 'I have tended to be spontaneous and fun-loving', 'I', 'मैं केंद्रित और गहन रहने की प्रवृत्ति रखता हूं', 'मैं सहज और मौज-मस्ती पसंद करने वाला रहा हूं'),
('5e306f1cb31adad40ccc8945', '5', 'I have been a hospitable person and have enjoyed welcoming new friends into my life', 'F', 'I have been a private person and have not mixed much with others', 'E', 'मैं एक मेहमाननवाज़ व्यक्ति रहा हूं और अपने जीवन में नए दोस्तों का स्वागत करते हुए मुझे आनंद आया है', 'मैं एक निजी व्यक्ति रहा हूं और दूसरों के साथ ज्यादा घुलता-मिलता नहीं हूं'),
('5e306f1cb31adad40ccc8946', '6', 'It\'s been difficult for me to relax and stop worrying about potential problems', 'B', 'It\'s been difficult for me to get myself worked up about potential problems', 'A', 'मेरे लिए आराम करना और संभावित समस्याओं के बारे में चिंता करना बंद करना कठिन हो गया है', 'मेरे लिए संभावित समस्याओं से निपटना कठिन हो गया है'),
('5e306f1cb31adad40ccc8947', '7', 'I\'ve been more of a \"street-smart\" survivor', 'G', 'I\'ve been more of a \"high-minded\" idealist', 'D', 'मैं अधिक \"स्ट्रीट-स्मार्ट\" उत्तरजीवी रहा हूँ', 'मैं अधिक \"उच्च विचारधारा\" वाला आदर्शवादी रहा हूँ'),
('5e306f1cb31adad40ccc8948', '8', 'I have needed to show affection to people', 'F', 'I have preferred to maintain some distance with people', 'H', 'मुझे लोगों के प्रति स्नेह दिखाने की जरूरत है', 'मैंने लोगों के साथ कुछ दूरी बनाए रखना पसंद किया है।\''),
('5e306f1cb31adad40ccc8949', '9', 'When presented with a new experience, I\'ve usually asked myself if it would be useful to me', 'C', 'When presented with a new experience, I\'ve usually asked myself if it would be enjoyable', 'I', 'जब मुझे कोई नया अनुभव मिलता है, तो मैं आमतौर पर खुद से पूछता हूं कि क्या यह मेरे लिए उपयोगी होगा', 'जब मुझे कोई नया अनुभव मिलता है, तो मैं आमतौर पर खुद से पूछता हूं कि क्या यह आनंददायक होगा'),
('5e306f1cb31adad40ccc894a', '10', 'I have tended to focus too much on myself', 'E', 'I have tended to focus too much on others', 'A', 'मैं खुद पर बहुत अधिक ध्यान केंद्रित करने लगा हूं', 'मैं दूसरों पर बहुत अधिक ध्यान केंद्रित करने लगा हूं'),
('5e306f1cb31adad40ccc894b', '11', 'Others have depended on my insight and knowledge', 'H', 'Others have depended on my strength and decisiveness', 'G', 'अन्य लोग मेरी अंतर्दृष्टि और ज्ञान पर निर्भर रहे हैं', 'दूसरे लोग मेरी ताकत और निर्णायक क्षमता पर निर्भर रहे हैं'),
('5e306f1cb31adad40ccc894c', '12', 'I have come across as being too unsure of myself', 'B', 'I have come across as being too sure of myself', 'D', 'मुझे अपने बारे में बहुत अधिक अनिश्चित होने का आभास हुआ है', 'मैं खुद को लेकर बहुत आश्वस्त हो गया हूं'),
('5e306f1cb31adad40ccc894d', '13', 'I have been more relationship-oriented than goal-oriented', 'F', 'I have been more goal-oriented than relationship-oriented', 'C', 'मैं लक्ष्य-उन्मुख से अधिक संबंध-उन्मुख रहा हूं', 'मैं संबंध-उन्मुख से अधिक लक्ष्य-उन्मुख रहा हूं'),
('5e306f1cb31adad40ccc894e', '14', 'I have not been able to speak up for myself very well', 'E', 'I have been outspoken – I\'ve said what others wished they had the nerve to say ', 'I', 'मैं अपने बारे में बहुत अच्छे से नहीं बोल पा रहा हूं', 'मैं मुखर रहा हूँ - मैंने वही कहा है जो दूसरे चाहते थे कि उनमें कहने का साहस होता'),
('5e306f1cb31adad40ccc894f', '15', 'It\'s been difficult for me to stop considering alternatives and do something definite', 'H', 'It\'s been difficult for me to take it easy and be more flexible', 'D', 'मेरे लिए विकल्पों पर विचार करना बंद करना और कुछ निश्चित करना कठिन हो गया है', 'मेरे लिए इसे सहजता से लेना और अधिक लचीला होना कठिन रहा है'),
('5e306f1cb31adad40ccc8950', '16', 'I have tended to be careful and hesitant ', 'B', 'I have tended to be bold and domineering ', 'G', 'मेरी प्रवृत्ति सावधान रहने और झिझकने की रही है', 'मेरी प्रवृत्ति साहसी और दबंग होने की रही है'),
('5e306f1cb31adad40ccc8951', '17', 'My reluctance to get too involved has gotten me into trouble with people ', 'A', 'My eagerness to have people depend on me has gotten me into trouble with them ', 'F', 'बहुत ज्यादा शामिल होने की मेरी अनिच्छा ने मुझे लोगों के साथ परेशानी में डाल दिया है', 'लोगों को मुझ पर निर्भर करने की मेरी उत्सुकता ने मुझे उनसे परेशानी में डाल दिया है'),
('5e306f1cb31adad40ccc8952', '18', 'Usually, I have been able to put my feelings aside to get the job done ', 'C', 'Usually, I have needed to work through my feelings before I could act', 'E', 'आमतौर पर, मैं काम पूरा करने के लिए अपनी भावनाओं को एक तरफ रखने में सक्षम हूं', 'आमतौर पर, मुझे अभिनय करने से पहले अपनी भावनाओं पर काम करना पड़ता है'),
('5e306f1cb31adad40ccc8953', '19', 'Generally, I\'ve been methodical and cautious', 'B', 'Generally, I\'ve been adventurous and taken risks ', 'I', 'आम तौर पर, मैं व्यवस्थित और सतर्क रहा हूं', 'आम तौर पर, मैं साहसी रहा हूँ और जोखिम लेता रहा हूँ'),
('5e306f1cb31adad40ccc8954', '20', 'I have tended to be a supportive, giving person who seeks intimacy with others ', 'F', 'I have tended to be a serious, reserved person who likes discussing issues ', 'D', 'मैं एक सहयोगी, देने वाला व्यक्ति बन गया हूं जो दूसरों के साथ घनिष्ठता चाहता है', 'मैं एक गंभीर, आरक्षित व्यक्ति रहा हूं जो मुद्दों पर चर्चा करना पसंद करता है'),
('5e306f1cb31adad40ccc8955', '21', 'I\'ve often felt the need to be a \"pillar of strength\" ', 'G', 'I\'ve often felt the need to perform perfectly ', 'C', 'मुझे अक्सर \"शक्ति का स्तंभ\" बनने की आवश्यकता महसूस हुई है', 'मुझे अक्सर उत्कृष्ट प्रदर्शन करने की आवश्यकता महसूस हुई है'),
('5e306f1cb31adad40ccc8956', '22', 'I\'ve typically been interested in asking tough questions and maintaining my independence ', 'H', 'I\'ve typically been interested in maintaining my stability and peace of mind ', 'A', 'मुझे आमतौर पर कठिन प्रश्न पूछने और अपनी स्वतंत्रता बनाए रखने में रुचि रही है', 'मैं आमतौर पर अपनी स्थिरता और मन की शांति बनाए रखने में रुचि रखता हूं'),
('5e306f1cb31adad40ccc8957', '23', 'I\'ve been a bit cynical and skeptical', 'B', 'I\'ve been a bit mushy and sentimental', 'F', 'मैं थोड़ा निंदक और संशयवादी हो गया हूं', 'मैं थोड़ा भावुक और भावुक हो गया हूं'),
('5e306f1cb31adad40ccc8958', '24', 'I\'ve often worried that I\'m missing out on something better ', 'I', 'I\'ve often worried that if I let down my guard, someone will take advantage of me ', 'G', 'मुझे अक्सर चिंता होती है कि मैं कुछ बेहतर करने से चूक रहा हूँ', 'मुझे अक्सर यह चिंता रहती है कि अगर मैंने अपनी सावधानी बरती तो कोई मेरा फायदा उठाएगा'),
('5e306f1cb31adad40ccc8959', '25', 'My habit of being \"stand-offish\" has annoyed people ', 'E', 'My habit of telling people what to do has annoyed people', 'D', 'मेरी \"स्टैंड-ऑफिश\" रहने की आदत ने लोगों को परेशान कर दिया है', 'लोगों को यह बताने की कि क्या करना है, मेरी आदत ने लोगों को नाराज़ कर दिया है'),
('5e306f1cb31adad40ccc895a', '26', 'I have tended to get anxious if there was too much excitement and stimulation', 'A', 'I have tended to get anxious if there wasn\'t enough excitement and stimulation ', 'I', 'यदि बहुत अधिक उत्साह और उत्तेजना हो तो मैं चिंतित हो जाता हूँ', 'यदि पर्याप्त उत्तेजना और उत्तेजना नहीं होती तो मैं चिंतित हो जाता हूँ'),
('5e306f1cb31adad40ccc895b', '27', 'I have depended on my friends and they have known that they can depend on me', 'B', 'I have not depended on people; I have done things on my own ', 'C', 'मैं अपने दोस्तों पर निर्भर रहा हूं और वे जानते हैं कि वे मुझ पर निर्भर रह सकते हैं', 'मैं लोगों पर निर्भर नहीं रहा हूं; मैंने चीजें अपने दम पर की हैं'),
('5e306f1cb31adad40ccc895c', '28', 'I have tended to be detached and preoccupied', 'H', 'I have tended to be moody and self-absorbed', 'E', 'मेरी प्रवृत्ति अलग और व्यस्त रहने की रही है', 'मैं मूडी और आत्म-लीन रहने की प्रवृत्ति रखता हूं'),
('5e306f1cb31adad40ccc895d', '29', 'I have liked to challenge people and \"shake them up\"', 'G', 'I have liked to comfort people and calm them down', 'F', 'मुझे लोगों को चुनौती देना और \"उन्हें हिला देना\" पसंद है', 'मुझे लोगों को सांत्वना देना और उन्हें शांत करना पसंद है'),
('5e306f1cb31adad40ccc895e', '30', 'I have generally been an outgoing, sociable person', 'I', 'I have generally been an earnest, self-disciplined person ', 'D', 'मैं आम तौर पर एक निवर्तमान, मिलनसार व्यक्ति रहा हूं', 'मैं आम तौर पर एक ईमानदार, आत्म-अनुशासित व्यक्ति रहा हूं'),
('5e306f1cb31adad40ccc895f', '31', 'I\'ve wanted to \"fit in\" with others-I get uncomfortable when I stand out too much', 'A', 'I\'ve wanted to stand out from others-I get uncomfortable when I don\'t distinguish myself', 'C', 'मैं दूसरों के साथ \"फिट\" होना चाहता हूं-जब मैं बहुत ज्यादा अलग दिखता हूं तो मैं असहज हो जाता हूं', 'मैं दूसरों से अलग दिखना चाहता हूं-जब मैं खुद को अलग नहीं दिखाता तो मैं असहज हो जाता हूं'),
('5e306f1cb31adad40ccc8960', '32', 'Pursuing my personal interests has been more important to me than having stability and security', 'H', 'Having stability and security has been more important to me than pursuing my personal interests', 'B', 'मेरे लिए स्थिरता और सुरक्षा की तुलना में अपने व्यक्तिगत हितों को पूरा करना अधिक महत्वपूर्ण रहा है', 'मेरे लिए अपने व्यक्तिगत हितों को आगे बढ़ाने की तुलना में स्थिरता और सुरक्षा अधिक महत्वपूर्ण रही है'),
('5e306f1cb31adad40ccc8961', '33', 'When I\'ve had conflicts with others, I\'ve tended to withdraw', 'E', 'When I\'ve had conflicts with others, I\'ve rarely backed down ', 'G', 'जब मेरा दूसरों के साथ विवाद होता है, तो मैं पीछे हटने की प्रवृत्ति रखता हूं', 'जब मेरा दूसरों के साथ टकराव हुआ है, तो मैं शायद ही कभी पीछे हटा हूं'),
('5e306f1cb31adad40ccc8962', '34', 'I have given in too easily and let others push me around', 'A', 'I have been too uncompromising and demanding with others', 'D', 'मैंने बहुत आसानी से हार मान ली है और दूसरों को मुझ पर दबाव डालने दिया है', 'मैं दूसरों के साथ बहुत ज्यादा समझौताहीन और मांग करने वाला रहा हूं'),
('5e306f1cb31adad40ccc8963', '35', 'I\'ve been appreciated for my unsinkable spirit and resourcefulness', 'I', 'I\'ve been appreciated for my deep caring and personal warmth', 'F', 'मेरी अदम्य भावना और साधन संपन्नता के लिए मेरी सराहना की गई है', 'मेरी गहरी देखभाल और व्यक्तिगत गर्मजोशी के लिए मेरी सराहना की गई है'),
('5e306f1cb31adad40ccc8964', '36', 'I have wanted to make a favorable impression on others', 'C', 'I have cared little about making a favorable impression on others ', 'H', 'मैं दूसरों पर अनुकूल प्रभाव डालना चाहता हूँ', 'मैंने दूसरों पर अनुकूल प्रभाव डालने की बहुत कम परवाह की है'),
('5e306f1cb31adad40ccc8965', '37', 'I\'ve depended on my perseverance and common sense ', 'B', 'I\'ve depended on my imagination and moments of inspiration ', 'E', 'मैं अपनी दृढ़ता और सामान्य ज्ञान पर निर्भर रहा हूं', 'मैं अपनी कल्पना और प्रेरणा के क्षणों पर निर्भर रहा हूं'),
('5e306f1cb31adad40ccc8966', '38', 'Basically, I have been easy-going and agreeable', 'A', 'Basically, I have been hard-driving and assertive', 'G', 'मूलतः, मैं सहज और सहमत रहने वाला व्यक्ति रहा हूँ', 'मूलतः, मैं कठोर और दृढ़ निश्चयी रहा हूँ'),
('5e306f1cb31adad40ccc8967', '39', 'I have worked hard to be accepted and well-liked', 'C', 'Being accepted and well-liked has not been a high priority for me ', 'D', 'मैंने स्वीकार किए जाने और पसंद किए जाने के लिए कड़ी मेहनत की है', 'स्वीकार्य और पसंद किया जाना मेरे लिए उच्च प्राथमिकता नहीं रही है'),
('5e306f1cb31adad40ccc8968', '40', 'In reaction to pressure from others, I have become more withdrawn', 'H', 'In reaction to pressure from others, I have become more assertive ', 'I', 'दूसरों के दबाव की प्रतिक्रिया में, मैं और अधिक पीछे हट गया हूँ', 'दूसरों के दबाव की प्रतिक्रिया में, मैं और अधिक मुखर हो गया हूँ'),
('5e306f1cb31adad40ccc8969', '41', 'People have been interested in me because I\'ve been outgoing, engaging, and interested in them', 'F', 'People have been interested in me because I\'ve been quiet, unusual, and deep ', 'E', 'लोगों की मुझमें दिलचस्पी इसलिए रही है क्योंकि मैं मिलनसार, आकर्षक और उनमें रुचि रखने वाला रहा हूं', 'लोगों की मुझमें दिलचस्पी इसलिए रही है क्योंकि मैं शांत, असामान्य और गहरा हूं'),
('5e306f1cb31adad40ccc896a', '42', 'Duty and responsibility have been important values for me', 'B', 'Harmony and acceptance have been important values for me', 'A', 'कर्तव्य और जिम्मेदारी मेरे लिए महत्वपूर्ण मूल्य रहे हैं', 'सद्भाव और स्वीकार्यता मेरे लिए महत्वपूर्ण मूल्य रहे हैं'),
('5e306f1cb31adad40ccc896b', '43', 'I\'ve tried to motivate people by making big plans and big promises', 'G', 'I\'ve tried to motivate people by pointing out the consequences of not following my advice', 'D', 'मैंने बड़ी योजनाएँ और बड़े वादे करके लोगों को प्रेरित करने का प्रयास किया है', 'मैंने लोगों को मेरी सलाह का पालन न करने के परिणामों के बारे में बताकर प्रेरित करने का प्रयास किया है'),
('5e306f1cb31adad40ccc896c', '44', 'I have seldom been emotionally demonstrative', 'H', 'I have often been emotionally demonstrative', 'F', 'मैं शायद ही कभी भावनात्मक रूप से प्रदर्शनकारी रहा हूँ', 'मैं अक्सर भावनात्मक रूप से प्रदर्शनकारी रहा हूं'),
('5e306f1cb31adad40ccc896d', '45', 'Dealing with details has not been one of my strong suits', 'I', 'I have excelled at dealing with details', 'C', 'विवरणों से निपटना मेरी मजबूत प्राथमिकताओं में से एक नहीं रहा है', 'मैंने विवरणों से निपटने में उत्कृष्टता हासिल की है'),
('5e306f1cb31adad40ccc896e', '46', 'I have often emphasized how different I am from most peoples, especially my family', 'E', 'I have often emphasized how much I have in common with most people, especially my family ', 'A', 'मैंने अक्सर इस बात पर ज़ोर दिया है कि मैं ज़्यादातर लोगों से, ख़ासकर अपने परिवार से कितना अलग हूं', 'मैंने अक्सर इस बात पर ज़ोर दिया है कि ज़्यादातर लोगों से, ख़ासकर अपने परिवार से, मुझमें कितनी समानताएं हैं'),
('5e306f1cb31adad40ccc896f', '47', 'When situations have gotten heated, I have tended to stay on the sidelines', 'H', 'When situations have gotten heated, I have tended to get right into the middle of things', 'G', 'जब स्थितियां गर्म हो जाती हैं, तो मैं किनारे पर रहने की प्रवृत्ति रखता हूं', 'जब स्थितियां गर्म हो जाती हैं, तो मैं सीधे चीजों के बीच में पहुंच जाता हूं'),
('5e306f1cb31adad40ccc8970', '48', 'I have stood by my friends, even when they have been wrong', 'G', 'I have not wanted to compromise what is right even for friendship', 'B', 'मैं अपने दोस्तों के साथ खड़ा रहा हूं, तब भी जब वे गलत थे', 'मैं दोस्ती के लिए भी जो सही है उससे समझौता नहीं करना चाहता'),
('5e306f1cb31adad40ccc8971', '49', 'I\'ve been a well-meaning supporter ', 'F', 'I\'ve been a highly-motivated go-getter', 'C', 'मैं एक नेक इरादे वाला समर्थक रहा हूं', 'मैं अत्यधिक प्रेरित होकर घूमने वाला व्यक्ति रहा हूं'),
('5e306f1cb31adad40ccc8972', '50', 'When troubled, I have tended to brood about my problems', 'E', 'When troubled, I have tended to find distractions for myself', 'I', 'परेशान होने पर, मैं अपनी समस्याओं के बारे में सोचने लगा हूँ', 'परेशान होने पर, मैं अपने लिए ध्यान भटकाने की कोशिश करता हूँ'),
('5e306f1cb31adad40ccc8973', '51', 'Generally, I\'ve had strong convictions and a sense of how things should be ', 'D', 'Generally, I\'ve had serious doubts and have questioned how things seemed to be', 'H', 'आम तौर पर, मेरे पास दृढ़ विश्वास और यह समझ है कि चीजें कैसी होनी चाहिए', 'आम तौर पर, मुझे गंभीर संदेह हुआ है और मैंने सवाल किया है कि चीजें कैसी दिख रही हैं'),
('5e306f1cb31adad40ccc8974', '52', 'I\'ve created problems with others by being pessimistic and complaining', 'B', 'I\'ve created problems with others by being bossy and controlling', 'G', 'मैंने निराशावादी होकर और शिकायत करके दूसरों के साथ समस्याएँ पैदा की हैं', 'मैंने दूसरों पर रौब दिखाकर और नियंत्रण करके उनके साथ समस्याएँ पैदा की हैं'),
('5e306f1cb31adad40ccc8975', '53', 'I have tended to act on my feelings and let the \"chips fall where they may\"', 'F', 'I have tended not to act on my feelings lest they stir up more problems', 'A', 'मैं अपनी भावनाओं के अनुरूप कार्य करने की प्रवृत्ति रखता हूँ और \"जहाँ संभव हो सके, समस्याएँ गिरने देता हूँ\"', 'मेरी आदत हो गई है कि मैं अपनी भावनाओं पर अमल नहीं करता, ऐसा न हो कि वे और अधिक समस्याएँ पैदा कर दें'),
('5e306f1cb31adad40ccc8976', '54', 'Being the center of attention has usually felt natural to me ', 'C', 'Being the center of attention has usually felt strange to me ', 'E', 'ध्यान का केंद्र बनना आमतौर पर मुझे स्वाभाविक लगता है', 'ध्यान का केंद्र बनना आमतौर पर मुझे अजीब लगता है'),
('5e306f1cb31adad40ccc8977', '55', 'I\'ve been careful, and have tried to prepare for unforeseen problems', 'B', 'I\'ve been spontaneous, and have preferred to improvise as problems come up', 'I', 'मैं सावधान रहा हूं और अप्रत्याशित समस्याओं के लिए तैयारी करने की कोशिश की है', 'मैं सहज रहा हूं और समस्याएं आने पर सुधार करना पसंद किया है'),
('5e306f1cb31adad40ccc8978', '56', 'I have gotten angry when others have not shown enough appreciation for what I have done for them', 'F', 'I have gotten angry when others have not listened to what I have told them', 'D', 'मुझे तब गुस्सा आता है जब दूसरों ने मैंने उनके लिए जो किया है, उसकी पर्याप्त सराहना नहीं की है', 'जब दूसरों ने मेरी बात नहीं मानी तो मुझे क्रोध आया'),
('5e306f1cb31adad40ccc8979', '57', 'Being independent and self-reliant has been important to me', 'G', 'Being valued and admired has been important to me', 'C', 'स्वतंत्र और आत्मनिर्भर होना मेरे लिए महत्वपूर्ण रहा है', 'महत्व दिया जाना और प्रशंसा पाना मेरे लिए महत्वपूर्ण रहा है'),
('5e306f1cb31adad40ccc897a', '58', 'When I\'ve debated with friends, I\'ve tended to press my arguments forcefully', 'H', 'When I\'ve debated with friends, I\'ve tended to let things go to prevent hard feelings', 'A', 'जब मैंने दोस्तों के साथ बहस की है, तो मैं अपने तर्कों को मजबूती से दबाने की प्रवृत्ति रखता हूं', 'जब मैंने दोस्तों के साथ बहस की है, तो मेरी प्रवृत्ति कठोर भावनाओं को रोकने के लिए चीजों को जाने देने की रही है'),
('5e306f1cb31adad40ccc897b', '59', 'I have often been possessive of loved ones--I have had trouble letting them be', 'F', 'I have often \"tested\" loved ones to see if they were really there for me', 'B', 'मैं अक्सर अपने प्रियजनों पर अधिकार जताता रहा हूं--मुझे उन्हें अपने पास रखने में परेशानी होती है', 'मैंने अक्सर प्रियजनों का \"परीक्षण\" किया है यह देखने के लिए कि क्या वे वास्तव में मेरे लिए हैं'),
('5e306f1cb31adad40ccc897c', '60', 'Organizing resources and making things happen has been one of my major strengths', 'G', 'I generally have tended to minimize my feelings and not pay very much attention to them   ', 'I', 'संसाधनों को व्यवस्थित करना और चीजों को संभव बनाना मेरी प्रमुख शक्तियों में से एक रही है', 'मैं आम तौर पर अपनी भावनाओं को कम करने और उन पर अधिक ध्यान न देने की प्रवृत्ति रखता हूँ'),
('5e306f1cb31adad40ccc897d', '61', 'I\'ve tended to be driven and very hard on myself', 'D', 'I\'ve tended to be too emotional and rather undisciplined', 'E', 'मैं प्रेरित हो गया हूं और खुद पर बहुत सख्त हूं', 'मैं अत्यधिक भावुक और अनुशासनहीन हो गया हूँ'),
('5e306f1cb31adad40ccc897e', '62', 'I have tried to keep my life fast-paced, intense, and exciting', 'I', 'I have tried to keep my life regular, stable, and peaceful', 'A', 'मैंने अपने जीवन को तेज़-तर्रार, गहन और रोमांचक बनाए रखने की कोशिश की है', 'मैंने अपने जीवन को नियमित, स्थिर और शांतिपूर्ण रखने का प्रयास किया है'),
('5e306f1cb31adad40ccc897f', '63', 'Even though I\'ve had successes, I\'ve tended to doubt my abilities', 'B', 'Even though I\'ve had setbacks, I\'ve had a lot of confidence in my abilities', 'C', 'हालाँकि मुझे सफलताएँ मिली हैं, फिर भी मैं अपनी क्षमताओं पर संदेह करने लगा हूँ', 'भले ही मुझे असफलताएँ मिलीं, लेकिन मुझे अपनी क्षमताओं पर बहुत भरोसा था'),
('5e306f1cb31adad40ccc8980', '64', 'I generally have tended to dwell on my feelings and to hold onto them for a long time', 'E', 'I generally have tended to minimize my feelings and not pay very much attention to them   ', 'H', 'मैं आम तौर पर अपनी भावनाओं पर ध्यान केंद्रित करने और उन्हें लंबे समय तक बनाए रखने की प्रवृत्ति रखता हूं', 'मैं आम तौर पर अपनी भावनाओं को कम करने और उन पर अधिक ध्यान न देने की प्रवृत्ति रखता हूँ'),
('5e306f1cb31adad40ccc8981', '65', 'I have provided many people with attention and nurturance', 'F', 'I have provided many people with direction and motivation', 'G', 'मैंने कई लोगों को ध्यान और पोषण प्रदान किया है', 'मैंने कई लोगों को दिशा और प्रेरणा प्रदान की है'),
('5e306f1cb31adad40ccc8982', '66', 'I\'ve been a bit serious and strict with myself', 'D', 'I\'ve been a bit free-wheeling and permissive with myself', 'I', 'मैं अपने प्रति थोड़ा गंभीर और सख्त रहा हूं', 'मैं अपने प्रति थोड़ा स्वतंत्र और अनुदार रहा हूँ'),
('5e306f1cb31adad40ccc8983', '67', 'I\'ve been self-assertive and driven to excel', 'C', 'I\'ve been modest and have been happy to go at my own pace', 'A', 'मैं आत्म-दृढ़ हूं और उत्कृष्टता प्राप्त करने के लिए प्रेरित हूं', 'मैं विनम्र रहा हूं और अपनी गति से चलने में खुश हूं'),
('5e306f1cb31adad40ccc8984', '68', 'I have been proud of my clarity and objectivity', 'H', 'I have been proud of my reliability and commitment', 'B', 'मुझे अपनी स्पष्टता और निष्पक्षता पर गर्व है', 'मुझे अपनी विश्वसनीयता और प्रतिबद्धता पर गर्व है'),
('5e306f1cb31adad40ccc8985', '69', 'I have spent a lot of time looking inward-understanding my feelings bas been important to me', 'E', 'I have not spent much time looking inward-getting things done has been important to me', 'G', 'मैंने अपने अंदर झाँकने और अपनी भावनाओं को समझने में बहुत समय बिताया है जो मेरे लिए महत्वपूर्ण रहा है', 'मैंने अंदर की ओर देखने में ज्यादा समय नहीं बिताया है-चीजें करना मेरे लिए महत्वपूर्ण रहा है'),
('5e306f1cb31adad40ccc8986', '70', 'Generally, I have thought of myself as a sunny, casual person', 'A', 'Generally, I have thought of myself as a serious, dignified person', 'D', 'आम तौर पर, मैंने खुद को एक खुशमिजाज, सामान्य व्यक्ति के रूप में सोचा है', 'आम तौर पर, मैंने खुद को एक गंभीर, प्रतिष्ठित व्यक्ति के रूप में सोचा है'),
('5e306f1cb31adad40ccc8987', '71', 'I\'ve had an agile mind and boundless energy', 'I', 'I\'ve had a caring heart and deep dedication', 'F', 'मेरे पास एक चंचल दिमाग और असीमित ऊर्जा है', 'मेरे पास देखभाल करने वाला दिल और गहरा समर्पण है'),
('5e306f1cb31adad40ccc8988', '72', 'I have pursued activities that had a substantial potential for reward and personal recognition', 'C', 'I have been willing to give up reward and personal recognition if it meant doing work I was really interested in', 'H', 'मैंने ऐसी गतिविधियाँ अपनाई हैं जिनमें पुरस्कार और व्यक्तिगत मान्यता की पर्याप्त संभावनाएँ थीं', 'अगर मुझे वह काम करना है जिसमें मेरी वास्तव में रुचि है तो मैं पुरस्कार और व्यक्तिगत मान्यता छोड़ने को तैयार हूं'),
('5e306f1cb31adad40ccc8989', '73', 'Fulfilling social obligations has seldom been high on my agenda', 'E', 'I have usually have taken my social obligations very seriously', 'B', 'सामाजिक दायित्वों को पूरा करना मेरे एजेंडे में शायद ही कभी ऊपर रहा हो', 'मैंने आमतौर पर अपने सामाजिक दायित्वों को बहुत गंभीरता से लिया है'),
('5e306f1cb31adad40ccc898a', '74', 'In most situations, I have preferred to take the lead', 'G', 'In most situations, I have preferred to let someone else take the lead', 'A', 'अधिकांश स्थितियों में, मैंने नेतृत्व करना पसंद किया है', 'ज्यादातर स्थितियों में, मैंने किसी और को नेतृत्व करने देना पसंद किया है'),
('5e306f1cb31adad40ccc898b', '75', 'Over the years, my values and lifestyle have changed several times', 'C', 'Over the years, my values and lifestyle have remained fairly consistent', 'D', 'इन वर्षों में, मेरे मूल्य और जीवनशैली कई बार बदली हैं', 'इन वर्षों में, मेरे मूल्य और जीवनशैली काफी सुसंगत रहे हैं'),
('5e306f1cb31adad40ccc898c', '76', 'Typically, I have not had much self-discipline', 'I', 'Typically, I have not had much connection with people', 'H', 'आमतौर पर, मुझमें ज्यादा आत्म-अनुशासन नहीं है', 'आमतौर पर मेरा लोगों से ज्यादा जुड़ाव नहीं रहा है'),
('5e306f1cb31adad40ccc898d', '77', 'I have tended to withhold my affection, and have wanted others to come into my world', 'E', 'I have tended to give my affection too freely, and have wanted to extend myself to others', 'F', 'मैं अपने स्नेह को रोककर रखता हूं और चाहता हूं कि दूसरे लोग मेरी दुनिया में आएं', 'मैं अपना स्नेह बहुत खुलकर देने की प्रवृत्ति रखता हूँ, और स्वयं को दूसरों तक फैलाना चाहता हूँ'),
('5e306f1cb31adad40ccc898e', '78', 'I have had a tendency to think of worst case scenarios', 'B', 'I have had a tendency to think that everything will work out for the best', 'A', 'मेरी सबसे बुरी स्थिति के बारे में सोचने की प्रवृत्ति रही है', 'मेरी यह सोचने की प्रवृत्ति रही है कि सब कुछ अच्छे से होगा'),
('5e306f1cb31adad40ccc898f', '79', 'People have trusted me because I am confident and can look out for them', 'G', 'People have trusted me because I am fair and will do what is right', 'D', 'लोगों ने मुझ पर भरोसा किया है क्योंकि मैं आश्वस्त हूं और उनका ख्याल रख सकता हूं', 'लोगों ने मुझ पर भरोसा किया है क्योंकि मैं निष्पक्ष हूं और जो सही होगा वही करूंगा'),
('5e306f1cb31adad40ccc8990', '80', 'Often, I have been so involved in my own projects that I have become isolated from others', 'H', 'Often, I have been so involved with others that I have neglected my own projects', 'F', 'अक्सर, मैं अपनी ही परियोजनाओं में इतना व्यस्त हो गया हूं कि मैं दूसरों से अलग-थलग हो गया हूं', 'अक्सर, मैं दूसरों के साथ इतना व्यस्त हो गया हूं कि मैंने अपनी खुद की परियोजनाओं की उपेक्षा कर दी है'),
('5e306f1cb31adad40ccc8991', '81', 'When meeting someone new, I have usually been poised and self-contained', 'C', 'When meeting someone new, I have usually been chatty and entertaining', 'I', 'किसी नए व्यक्ति से मिलते समय, मैं आमतौर पर शांत और आत्म-निहित रहता हूँ', 'किसी नए व्यक्ति से मिलते समय, मैं आमतौर पर बातचीत और मनोरंजन करता रहा हूँ'),
('5e306f1cb31adad40ccc8992', '82', 'Generally speaking, I have tended to be pessimistic', 'E', 'Generally speaking, I have tended to be optimistic', 'A', 'सामान्यतया, मैं निराशावादी हो गया हूँ', 'सामान्यतया, मैं आशावादी रहा हूँ'),
('5e306f1cb31adad40ccc8993', '83', 'I have preferred to inhabit my own little world', 'H', 'I have preferred to let the world know I\'m here', 'G', 'मैंने अपनी छोटी सी दुनिया में रहना पसंद किया है', 'मैंने दुनिया को यह बताना पसंद किया है कि मैं यहां हूं'),
('5e306f1cb31adad40ccc8994', '84', 'I have often been troubled by nervousness, insecurity, and doubt', 'B', 'I have often been troubled by anger, perfectionism, and impatience', 'D', 'मैं अक्सर घबराहट, असुरक्षा और संदेह से परेशान रहा हूं', 'मैं अक्सर क्रोध, पूर्णतावाद और अधीरता से परेशान रहा हूँ'),
('5e306f1cb31adad40ccc8995', '85', 'I realize that I have often been too personal and intimate', 'F', 'I realize that I have often been too distant and aloof', 'C', 'मुझे एहसास है कि मैं अक्सर बहुत अधिक व्यक्तिगत और अंतरंग रहा हूँ', 'मुझे एहसास है कि मैं अक्सर बहुत दूर और अलग-थलग रहा हूं'),
('5e306f1cb31adad40ccc8996', '86', 'I have lost out because I have not felt up to taking opportunities', 'E', 'I have lost out because I have pursued too many possibilities', 'I', 'मैं हार गया हूं क्योंकि मैं अवसरों का लाभ उठाने में सक्षम नहीं हूं', 'मैं हार गया हूं क्योंकि मैंने बहुत सारी संभावनाओं का पीछा किया है'),
('5e306f1cb31adad40ccc8997', '87', 'I have tended to take a long time to get into action', 'H', 'I have tended to get into action quickly', 'D', 'मुझे कार्रवाई करने में काफी समय लग गया है', 'मेरी प्रवृत्ति शीघ्रता से कार्रवाई में जुट जाने की रही है'),
('5e306f1cb31adad40ccc8998', '88', 'I usually have had difficulty making decisions', 'B', 'I seldom have had difficulty making decisions', 'G', 'मुझे आमतौर पर निर्णय लेने में कठिनाई होती है', 'मुझे निर्णय लेने में शायद ही कभी कठिनाई हुई हो'),
('5e306f1cb31adad40ccc8999', '89', 'I have had a tendency to come on a little too strong with people', 'F', 'I have had a tendency not to assert myself enough with people', 'A', 'मेरी लोगों के साथ कुछ ज्यादा ही सख्ती से पेश आने की प्रवृत्ति रही है', 'मेरी यह प्रवृत्ति रही है कि मैं लोगों के सामने अपने आप को पर्याप्त रूप से व्यक्त नहीं कर पाता'),
('5e306f1cb31adad40ccc899a', '90', 'Typically, I have been even-tempered', 'C', 'Typically, I have had strong changes of mood ', 'E', 'आमतौर पर, मैं सम स्वभाव का रहा हूँ', 'आमतौर पर, मेरे मूड में तीव्र परिवर्तन हुए हैं'),
('5e306f1cb31adad40ccc899b', '91', 'When I\'ve been unsure of what to do, I\'ve often sought the advice of others', 'B', 'When I\'ve been unsure of what to do, I\'ve tried different things to see what worked best for me', 'I', 'जब मैं अनिश्चित होता हूँ कि क्या करूँ, तो मैं अक्सर दूसरों से सलाह लेता हूँ', 'जब मैं अनिश्चित हो गया कि क्या करूँ, तो मैंने यह देखने के लिए अलग-अलग चीज़ें आज़माईं कि मेरे लिए सबसे अच्छा क्या काम करता है'),
('5e306f1cb31adad40ccc899c', '92', 'I have worried that I would be left out of other\'s activities', 'F', 'I have worried that others\' activities would distract me from what I had to do', 'D', 'मुझे चिंता है कि मुझे दूसरों की गतिविधियों से वंचित कर दिया जाएगा', 'मुझे चिंता है कि दूसरों की गतिविधियाँ मुझे जो करना है उससे मेरा ध्यान भटका देंगी'),
('5e306f1cb31adad40ccc899d', '93', 'Typically, when I have gotten angry, I have told people off ', 'G', 'Typically, when I have gotten angry, I have become distant', 'C', 'आमतौर पर, जब मुझे गुस्सा आता है तो मैं लोगों को मना कर देता हूं', 'आमतौर पर, जब मुझे गुस्सा आता है तो मैं दूर हो जाता हूं'),
('5e306f1cb31adad40ccc899e', '94', 'I\'ve tended to have trouble falling asleep', 'H', 'I\'ve tended to fall asleep easily', 'A', 'मुझे सोने में परेशानी होने लगी है', 'मेरी आदत आसानी से सो जाने की हो गई है'),
('5e306f1cb31adad40ccc899f', '95', 'I have often tried to figure out how I could get closer to others', 'F', 'I have often tried to figure out what others want from me', 'B', 'मैंने अक्सर यह जानने की कोशिश की है कि मैं दूसरों के करीब कैसे आ सकता हूं', 'मैंने अक्सर यह जानने की कोशिश की है कि दूसरे मुझसे क्या चाहते हैं'),
('5e306f1cb31adad40ccc89a0', '96', 'I have usually been measured, straight-talking, and deliberate', 'G', 'I have usually been excitable, fast-talking, and witty', 'I', 'मैं आमतौर पर नपा-तुला, सीधी बात करने वाला और विचारशील रहा हूं', 'मैं आमतौर पर उत्तेजित, तेजी से बात करने वाला और मजाकिया रहा हूं'),
('5e306f1cb31adad40ccc89a1', '97', 'Often, I have not spoken up when I\'ve seen others making a mistake', 'E', 'Often, I have helped others see that they are making a mistake', 'D', 'अक्सर, जब मैंने दूसरों को गलती करते देखा है तो मैंने कुछ नहीं बोला है', 'अक्सर, मैंने दूसरों को यह देखने में मदद की है कि वे गलती कर रहे हैं'),
('5e306f1cb31adad40ccc89a2', '98', 'During most of my life, I have been a stormy person who has had maily volatile feelings', 'I', 'During most of my life, I have been a steady person in whom \"still waters run deep\"', 'A', 'अपने अधिकांश जीवन के दौरान, मैं एक मजबूत व्यक्ति रहा हूँ जिसकी भावनाएँ मुख्यतः अस्थिर रही हैं', 'अपने जीवन के अधिकांश समय में, मैं एक स्थिर व्यक्ति रहा हूँ जिसमें \"शांत पानी गहरा बहता है\"'),
('5e306f1cb31adad40ccc89a3', '99', 'When I have disliked people, I have usually tried hard to stay cordial-despite my feelings', 'C', 'When I have disliked people, I have usually let them know it-one way or another', 'B', 'जब मैंने लोगों को नापसंद किया है, तो मैंने आम तौर पर अपनी भावनाओं के बावजूद सौहार्दपूर्ण बने रहने की भरपूर कोशिश की है', 'जब मैंने लोगों को नापसंद किया है, तो मैंने आमतौर पर उन्हें यह बता दिया है - किसी न किसी तरीके से'),
('5e306f1cb31adad40ccc89a4', '100', 'Much of my difficulty with people has come from my touchiness and taking everything too personally', 'E', 'Much of my difficulty with people has come from my not caring about social conventions ', 'H', 'लोगों के साथ मेरी अधिकांश कठिनाई मेरी स्पर्शशीलता और हर चीज़ को व्यक्तिगत रूप से लेने के कारण आई है', 'लोगों के साथ मेरी अधिकांश कठिनाई सामाजिक परंपराओं की परवाह न करने के कारण आई है'),
('5e306f1cb31adad40ccc89a5', '101', 'My approach has been to jump in and rescue people', 'F', 'My approach has been to show people how to help themselves', 'G', 'मेरा दृष्टिकोण कूदकर लोगों को बचाने का रहा है', 'मेरा दृष्टिकोण लोगों को यह दिखाना है कि वे अपनी मदद कैसे करें'),
('5e306f1cb31adad40ccc89a6', '102', 'Generally, I have enjoyed \"letting go\" and pushing the limits', 'I', 'Generally, I have not enjoyed losing control of myself very much', 'D', 'आम तौर पर, मैंने \"जाने देना\" और सीमाएं लांघना पसंद किया है', 'आम तौर पर, मुझे ख़ुद पर नियंत्रण खोने में ज़्यादा मज़ा नहीं आता'),
('5e306f1cb31adad40ccc89a7', '103', 'I\'ve been overly concerned with doing better than others', 'C', 'I\'ve been overly concerned with making things okay for others ', 'A', 'मैं दूसरों से बेहतर करने को लेकर अत्यधिक चिंतित रहा हूं', 'मैं दूसरों के लिए चीजें ठीक करने को लेकर अत्यधिक चिंतित रहा हूं'),
('5e306f1cb31adad40ccc89a8', '104', 'My thoughts generally have been speculative-involving, my imagination and curiosity', 'H', 'My thoughts generally have been practical-just trying to keep things going', 'B', 'मेरे विचार आमतौर पर कल्पना और जिज्ञासा से युक्त रहे हैं', 'मेरे विचार आम तौर पर व्यावहारिक रहे हैं-बस चीजों को चालू रखने की कोशिश करना'),
('5e306f1cb31adad40ccc89a9', '105', 'One of my main assets has been my ability to take charge of situations', 'G', 'One of my main assets has been my ability to describe internal states ', 'E', 'मेरी मुख्य संपत्तियों में से एक स्थितियों को संभालने की मेरी क्षमता रही है', 'मेरी मुख्य संपत्तियों में से एक आंतरिक स्थितियों का वर्णन करने की मेरी क्षमता रही है'),
('5e306f1cb31adad40ccc89aa', '106', 'I have pushed to get things done correctly, even if it made people uncomfortable', 'D', 'I have not liked feeling pressured, so I have not liked pressuring anyone else', 'A', 'मैंने चीजों को सही तरीके से करने पर जोर दिया है, भले ही इससे लोगों को असुविधा हुई हो', 'मुझे दबाव महसूस करना पसंद नहीं है, इसलिए मुझे किसी और पर दबाव डालना पसंद नहीं है'),
('5e306f1cb31adad40ccc89ab', '107', 'I\'ve often taken pride in how important I run in others\' lives', 'F', 'I\'ve often taken pride in my gusto and openness to new experiences', 'I', 'मुझे अक्सर इस बात पर गर्व होता है कि मैं दूसरों के जीवन में कितना महत्वपूर्ण भूमिका निभाता हूँ', 'मुझे अक्सर अपने उत्साह और नए अनुभवों के प्रति खुलेपन पर गर्व होता है'),
('5e306f1cb31adad40ccc89ac', '108', 'I have perceived that I\'ve often come across to others as presentable, even admirable', 'C', 'I have perceived that I\'ve often come across to others as unusual, even odd', 'H', 'मैंने महसूस किया है कि मैं अक्सर दूसरों के सामने प्रस्तुत करने योग्य, यहाँ तक कि प्रशंसनीय के रूप में सामने आता हूँ', 'मैंने महसूस किया है कि मैं अक्सर दूसरों के सामने असामान्य, यहाँ तक कि अजीब भी आया हूँ'),
('5e306f1cb31adad40ccc89ad', '109', 'I have mostly done what I had to do', 'B', 'I have mostly done what I wanted to do', 'E', 'मैंने ज़्यादातर वही किया है जो मुझे करना था', 'मैंने ज़्यादातर वही किया है जो मैं करना चाहता था'),
('5e306f1cb31adad40ccc89ae', '110', 'I have usually enjoyed high-pressure, even difficult, situations', 'G', 'I have usually disliked being in high-pressure, even difficult, situations', 'A', 'मैंने आमतौर पर उच्च दबाव, यहां तक कि कठिन परिस्थितियों का भी आनंद लिया है', 'मुझे आमतौर पर उच्च दबाव, यहां तक कि कठिन परिस्थितियों में रहना पसंद नहीं है'),
('5e306f1cb31adad40ccc89af', '111', 'I\'ve been proud of my ability to be flexible-what\'s appropriate or important often changes', 'C', 'I\'ve been proud of my ability to take a stand-I\'ve been firm about what I believe in ', 'D', 'मुझे लचीला होने की अपनी क्षमता पर गर्व है - जो उचित या महत्वपूर्ण है वह अक्सर बदलता रहता है', 'मुझे अपना रुख अपनाने की क्षमता पर गर्व है-मैं जिस चीज में विश्वास करता हूं, उस पर दृढ़ हूं'),
('5e306f1cb31adad40ccc89b0', '112', 'My style has leaned toward spareness and austerity', 'H', 'My style has leaned toward excess and over-doing things', 'I', 'मेरी शैली संयम और मितव्ययता की ओर झुक गई है', 'मेरी शैली अति और जरूरत से ज्यादा काम करने की ओर झुक गई है'),
('5e306f1cb31adad40ccc89b1', '113', 'My own health and well-being have suffered because of my strong desire to help others ', 'F', 'My relationships have suffered because of my strong desire to attend to my personal needs', 'E', 'दूसरों की मदद करने की मेरी प्रबल इच्छा के कारण मेरा अपना स्वास्थ्य और खुशहाली प्रभावित हुई है', 'मेरी निजी ज़रूरतों को पूरा करने की मेरी प्रबल इच्छा के कारण मेरे रिश्तों पर असर पड़ा है'),
('5e306f1cb31adad40ccc89b2', '114', 'Generally speaking, I\'ve been too open and naive', 'A', 'Generally speaking, I\'ve been too wary and guarded', 'B', 'सामान्यतया, मैं बहुत खुला और अनुभवहीन रहा हूँ', 'सामान्यतया, मैं बहुत अधिक सावधान और सतर्क रहता हूँ'),
('5e306f1cb31adad40ccc89b3', '115', 'I have sometimes put people off by being too aggressive', 'G', 'I have sometimes put people off by being too \"up-tight\"', 'D', 'मैंने कभी-कभी अत्यधिक आक्रामक होकर लोगों को हतोत्साहित किया है', 'मैंने कभी-कभी बहुत अधिक \"सख्त\" होकर लोगों को हतोत्साहित किया है'),
('5e306f1cb31adad40ccc89b4', '116', 'Being of service and attending to the needs of others has been a high priority for me', 'F', 'Finding alternative ways of seeing and doing things has been a high priority for me', 'H', 'सेवा में रहना और दूसरों की जरूरतों को पूरा करना मेरे लिए उच्च प्राथमिकता रही है', 'चीजों को देखने और करने के वैकल्पिक तरीके खोजना मेरे लिए उच्च प्राथमिकता रही है'),
('5e306f1cb31adad40ccc89b5', '117', 'I\'ve been single-minded and persistent in pursuing my goals', 'C', 'I\'ve preferred to explore various courses of action to see where they lead', 'I', 'मैं अपने लक्ष्यों को प्राप्त करने के लिए एकनिष्ठ और दृढ़ रहा हूं', 'मैंने यह देखने के लिए कार्रवाई के विभिन्न तरीकों का पता लगाना पसंद किया है कि वे किस ओर ले जाते हैं'),
('5e306f1cb31adad40ccc89b6', '118', 'I have frequently been drawn to situations that stir up deep, intense emotions', 'E', 'I have frequently been drawn to situations that make me feel calm and at ease', 'A', 'मैं अक्सर ऐसी स्थितियों की ओर आकर्षित हुआ हूं जो गहरी, तीव्र भावनाएं जगाती हैं', 'मैं अक्सर ऐसी स्थितियों की ओर आकर्षित होता हूं जो मुझे शांत और सहज महसूस कराती हैं'),
('5e306f1cb31adad40ccc89b7', '119', 'I have cared less about practical results than about pursuing my interests', 'H', 'I have been practical and have expected my work to have concrete results', 'G', 'मैंने अपने हितों को आगे बढ़ाने की तुलना में व्यावहारिक परिणामों की कम परवाह की है', 'मैं व्यावहारिक रहा हूं और उम्मीद करता हूं कि मेरे काम के ठोस नतीजे आएं'),
('5e306f1cb31adad40ccc89b8', '120', 'I have had a deep need to belong', 'B', 'I have had a deep need to feel balanced', 'D', 'मुझे इससे संबंधित होने की गहरी आवश्यकता है', 'मुझे संतुलित महसूस करने की गहरी आवश्यकता है'),
('5e306f1cb31adad40ccc89b9', '121', 'In the past, I\'ve probably insisted on too much closeness in my friendships', 'F', 'In the past, I\'ve probably kept too much distance in my friendships', 'C', 'अतीत में, मैंने संभवतः अपनी मित्रता में बहुत अधिक निकटता पर जोर दिया है', 'अतीत में, मैंने संभवतः अपनी मित्रता में बहुत अधिक दूरी बनाए रखी है'),
('5e306f1cb31adad40ccc89ba', '122', 'I\'ve had a tendency to keep thinking about things from the past', 'E', 'I\'ve had a tendency to keep anticipating things I\'m going to do', 'I', 'मेरी अतीत की चीज़ों के बारे में सोचते रहने की प्रवृत्ति रही है', 'मेरी प्रवृत्ति रही है कि मैं जो कुछ करने जा रहा हूँ उसका पूर्वानुमान लगाता रहता हूँ'),
('5e306f1cb31adad40ccc89bb', '123', 'I\'ve tended to see people as intrusive and demanding', 'H', 'I\'ve tended to see people as disorganized and irresponsible', 'D', 'मैं लोगों को घुसपैठिया और मांग करने वाला मानता हूं', 'मैं लोगों को असंगठित और गैर-जिम्मेदार मानता हूं'),
('5e306f1cb31adad40ccc89bc', '124', 'Generally, I have not had much confidence in myself', 'B', 'Generally, I have had confidence only in myself', 'G', 'आम तौर पर, मुझे खुद पर ज्यादा भरोसा नहीं है', 'आमतौर पर मुझे खुद पर ही भरोसा रहा है'),
('5e306f1cb31adad40ccc89bd', '125', 'I\'ve probably been too passive and uninvolved', 'A', 'I\'ve probably been too controlling and manipulative', 'F', 'मैं संभवतः बहुत अधिक निष्क्रिय और असंबद्ध हो गया हूँ', 'मैं शायद बहुत अधिक नियंत्रित और चालाकी करने वाला रहा हूँ'),
('5e306f1cb31adad40ccc89be', '126', 'I\'ve frequently been stopped in my tracks by my self-doubt', 'E', 'I\'ve rarely let self-doubt stand in my way', 'C', 'मुझे अक्सर अपने ट्रैक में आत्म-संदेह के कारण रोका गया है', 'मैंने शायद ही कभी आत्म-संदेह को अपने रास्ते में आने दिया हो'),
('5e306f1cb31adad40ccc89bf', '127', 'Given a choice between something familiar and something new, I\'ve usually chosen something new', 'I', 'I\'ve generally chosen what I knew I already liked: why be disappointed with something I might not like?', 'B', 'कुछ परिचित और कुछ नए के बीच विकल्प को देखते हुए, मैंने आमतौर पर कुछ नया चुना है', 'मैंने आम तौर पर वही चुना है जो मुझे पता था कि मुझे पहले से ही पसंद है: किसी ऐसी चीज़ से निराश क्यों होना जो मुझे पसंद नहीं है?'),
('5e306f1cb31adad40ccc89c0', '128', 'I have given a lot of physical contact to reassure others about how I feel about them', 'F', 'I have generally felt that real love does not depend on physical contact', 'D', 'मैंने दूसरों को आश्वस्त करने के लिए कि मैं उनके बारे में कैसा महसूस करता हूं, बहुत अधिक शारीरिक संपर्क किया है', 'मैंने आम तौर पर महसूस किया है कि सच्चा प्यार शारीरिक संपर्क पर निर्भर नहीं करता है'),
('5e306f1cb31adad40ccc89c1', '129', 'When I\'ve needed to confront someone, I\'ve often been too harsh and direct', 'G', 'When I\'ve needed to confront someone, I\'ve often \"beaten around the bush\" too much', 'C', 'जब मुझे किसी का सामना करना पड़ता है, तो मैं अक्सर बहुत कठोर और सीधा हो जाता हूं', 'जब मुझे किसी का सामना करना पड़ता है, तो मैं अक्सर बहुत ज्यादा इधर-उधर की बातें करता हूँ'),
('5e306f1cb31adad40ccc89c2', '130', 'I have been attracted to subjects that others would probably find disturbing, even frightening', 'H', 'I have preferred not to spend my time dwelling on disturbing, frightening subjects', 'A', 'मैं उन विषयों के प्रति आकर्षित हुआ हूं जो दूसरों को संभवतः परेशान करने वाले, यहां तक कि भयावह भी लगेंगे', 'मैंने परेशान करने वाले, डरावने विषयों पर अपना समय बर्बाद नहीं करना पसंद किया है'),
('5e306f1cb31adad40ccc89c3', '131', 'I have gotten into trouble with people by being too intrusive and interfering', 'F', 'I have gotten into trouble with people by being too evasive and uncommunicative', 'B', 'मैं बहुत ज्यादा आक्रामक और हस्तक्षेप करके लोगों के साथ परेशानी में पड़ गया हूं', 'मैं बहुत ज्यादा दखलअंदाजी करके लोगों से परेशानी में पड़ गया हूं और मैं बहुत ज्यादा टाल-मटोल करने वाला और संवादहीन होकर लोगों से परेशानी में पड़ गया हूं'),
('5e306f1cb31adad40ccc89c4', '132', 'I\'ve worried that I don\'t have the resources to fulfill the responsibilities I\'ve taken on', 'G', 'I\'ve worried that I don\'t have the self-discipline to focus on what will really fulfill me', 'I', 'मुझे चिंता है कि जो जिम्मेदारियां मैंने उठाई हैं उन्हें पूरा करने के लिए मेरे पास संसाधन नहीं हैं', 'मुझे चिंता है कि मेरे पास इस बात पर ध्यान केंद्रित करने के लिए आत्म-अनुशासन नहीं है कि वास्तव में मुझे क्या पूरा करेगा'),
('5e306f1cb31adad40ccc89c5', '133', 'Generally, I\'ve been a highly intuitive, individualistic person', 'E', 'Generally, I\'ve been a highly organized, responsible person', 'D', 'आम तौर पर, मैं अत्यधिक अंतर्ज्ञानी, व्यक्तिवादी व्यक्ति रहा हूं', 'आम तौर पर, मैं एक अत्यधिक संगठित, जिम्मेदार व्यक्ति रहा हूँ'),
('5e306f1cb31adad40ccc89c6', '134', 'Overcoming inertia has been one of my main problems', 'A', 'Being unable to slow down has been one of my main problems', 'I', 'जड़ता पर काबू पाना मेरी मुख्य समस्याओं में से एक रही है', 'गति धीमी न कर पाना मेरी मुख्य समस्याओं में से एक रही है'),
('5e306f1cb31adad40ccc89c7', '135', 'When I\'ve felt insecure, I\'ve reacted by becoming arrogant and dismissive', 'C', 'When I\'ve felt insecure, I\'ve reacted by becoming defensive and argumentative', 'B', 'जब मैंने असुरक्षित महसूस किया है, तो मैंने अहंकारी और उपेक्षापूर्ण बनकर प्रतिक्रिया व्यक्त की है', 'जब भी मैंने असुरक्षित महसूस किया है, मैंने रक्षात्मक और तर्कशील बनकर प्रतिक्रिया व्यक्त की है'),
('5e306f1cb31adad40ccc89c8', '136', 'I have generally been open-minded and willing to try new approaches', 'H', 'I have generally been self-revealing and willing to share my feelings with others', 'E', 'मैं आम तौर पर खुले विचारों वाला रहा हूं और नए तरीकों को आजमाने का इच्छुक रहा हूं', 'मैं आम तौर पर आत्म-प्रकटीकरण करता रहा हूं और अपनी भावनाओं को दूसरों के साथ साझा करने को तैयार रहता हूं'),
('5e306f1cb31adad40ccc89c9', '137', 'I\'ve presented myself to others as tougher than I really am', 'G', 'I\'ve presented myself to others as caring more than I really do', 'F', 'मैंने खुद को दूसरों के सामने उतना ही सख्त पेश किया है जितना मैं वास्तव में हूं', 'मैंने स्वयं को दूसरों के सामने अपनी अपेक्षा अधिक परवाह करने वाला प्रस्तुत किया है'),
('5e306f1cb31adad40ccc89ca', '138', 'I usually have followed my conscience and reason', 'D', 'I usually have followed my feelings and impulses', 'I', 'मैंने आमतौर पर अपने विवेक और तर्क का पालन किया है', 'मैंने आमतौर पर अपनी भावनाओं और आवेगों का अनुसरण किया है'),
('5e306f1cb31adad40ccc89cb', '139', 'Serious adversity has made me feel hardened and resolute', 'C', 'Serious adversity has made me feel discouraged and resigned', 'A', 'गंभीर प्रतिकूल परिस्थितियों ने मुझे कठोर और दृढ़ महसूस कराया है', 'गंभीर प्रतिकूलता ने मुझे हतोत्साहित कर दिया और इस्तीफा दे दिया'),
('5e306f1cb31adad40ccc89cc', '140', 'I usually have made sure that I had some kind of \"safety net\" to fall back on', 'B', 'I usually have chosen to live on the edge and to depend on as little as possible', 'H', 'मैंने आमतौर पर यह सुनिश्चित किया है कि मेरे पास वापस आने के लिए किसी प्रकार का \"सुरक्षा जाल\" हो', 'मैंने आमतौर पर किनारे पर रहना और जितना संभव हो सके कम पर निर्भर रहना चुना है'),
('5e306f1cb31adad40ccc89cd', '141', 'I\'ve had to be strong for others, so I haven\'t had time to deal with my feelings and fears', 'G', 'I\'ve had difficulty coping with my feelings and fears, so it\'s been hard for me to be strong for others', 'E', 'मुझे दूसरों के लिए मजबूत बनना पड़ा है, इसलिए मेरे पास अपनी भावनाओं और डर से निपटने का समय नहीं है', 'मुझे अपनी भावनाओं और डर से निपटने में कठिनाई हो रही है, इसलिए मेरे लिए दूसरों के लिए मजबूत होना कठिन हो गया है'),
('5e306f1cb31adad40ccc89ce', '142', 'I have often wondered why people focus on the negative when there is so much that\'s wonderful about life', 'A', 'I have often wondered why people are so happy when so much in life is messed up', 'D', 'मुझे अक्सर आश्चर्य होता है कि लोग नकारात्मक बातों पर ध्यान क्यों केंद्रित करते हैं जबकि जीवन में इतना कुछ अद्भुत है', 'मुझे अक्सर आश्चर्य होता है कि जब जीवन में इतना कुछ गड़बड़ है तो लोग इतने खुश क्यों होते हैं'),
('5e306f1cb31adad40ccc89cf', '143', 'I have tried hard not to be seen as a selfish person', 'F', 'I have tried hard not to be seen as a boring person', 'I', 'मैंने बहुत कोशिश की है कि मुझे एक स्वार्थी व्यक्ति के रूप में न देखा जाए', 'मैंने बहुत कोशिश की है कि मुझे एक उबाऊ व्यक्ति के रूप में न देखा जाए'),
('5e306f1cb31adad40ccc89d0', '144', 'I have avoided intimacy when I feared I would be overwhelmed by people\'s needs and demands', 'H', 'I have avoided intimacy when I feared I would not be able to live up to people\'s expectations of me', 'C', 'जब मुझे डर था कि मैं लोगों की ज़रूरतों और मांगों से अभिभूत हो जाऊँगा तो मैंने अंतरंगता से परहेज़ किया है', 'जब मुझे डर था कि मैं लोगों की अपेक्षाओं पर खरा नहीं उतर पाऊंगा तो मैंने अंतरंगता से दूरी बना ली है');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
